// Code generated by protoc-gen-go. DO NOT EDIT.
// source: echo_server.proto

package echo_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HttpRequestDump struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PostData             string            `protobuf:"bytes,3,opt,name=post_data,json=postData,proto3" json:"post_data,omitempty"`
	Method               string            `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *HttpRequestDump) Reset()         { *m = HttpRequestDump{} }
func (m *HttpRequestDump) String() string { return proto.CompactTextString(m) }
func (*HttpRequestDump) ProtoMessage()    {}
func (*HttpRequestDump) Descriptor() ([]byte, []int) {
	return fileDescriptor_f24ecbb5972b7a26, []int{0}
}

func (m *HttpRequestDump) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HttpRequestDump.Unmarshal(m, b)
}
func (m *HttpRequestDump) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HttpRequestDump.Marshal(b, m, deterministic)
}
func (m *HttpRequestDump) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HttpRequestDump.Merge(m, src)
}
func (m *HttpRequestDump) XXX_Size() int {
	return xxx_messageInfo_HttpRequestDump.Size(m)
}
func (m *HttpRequestDump) XXX_DiscardUnknown() {
	xxx_messageInfo_HttpRequestDump.DiscardUnknown(m)
}

var xxx_messageInfo_HttpRequestDump proto.InternalMessageInfo

func (m *HttpRequestDump) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *HttpRequestDump) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *HttpRequestDump) GetPostData() string {
	if m != nil {
		return m.PostData
	}
	return ""
}

func (m *HttpRequestDump) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func init() {
	proto.RegisterType((*HttpRequestDump)(nil), "echo_server.HttpRequestDump")
	proto.RegisterMapType((map[string]string)(nil), "echo_server.HttpRequestDump.HeadersEntry")
}

func init() { proto.RegisterFile("echo_server.proto", fileDescriptor_f24ecbb5972b7a26) }

var fileDescriptor_f24ecbb5972b7a26 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x4d, 0xce, 0xc8,
	0x8f, 0x2f, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46,
	0x12, 0x52, 0xba, 0xc9, 0xc8, 0xc5, 0xef, 0x51, 0x52, 0x52, 0x10, 0x94, 0x5a, 0x58, 0x9a, 0x5a,
	0x5c, 0xe2, 0x52, 0x9a, 0x5b, 0x20, 0x24, 0xc0, 0xc5, 0x5c, 0x5a, 0x94, 0x23, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0x04, 0x62, 0x0a, 0x39, 0x73, 0xb1, 0x67, 0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x15,
	0x4b, 0x30, 0x29, 0x30, 0x6b, 0x70, 0x1b, 0x69, 0xea, 0x21, 0x9b, 0x8b, 0x66, 0x80, 0x9e, 0x07,
	0x44, 0xad, 0x6b, 0x5e, 0x49, 0x51, 0x65, 0x10, 0x4c, 0xa7, 0x90, 0x34, 0x17, 0x67, 0x41, 0x7e,
	0x71, 0x49, 0x7c, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0x33, 0xd8, 0x70, 0x0e, 0x90, 0x80, 0x4b, 0x62,
	0x49, 0xa2, 0x90, 0x18, 0x17, 0x5b, 0x6e, 0x6a, 0x49, 0x46, 0x7e, 0x8a, 0x04, 0x0b, 0x58, 0x06,
	0xca, 0x93, 0xb2, 0xe2, 0xe2, 0x41, 0x36, 0x0d, 0xe4, 0xb6, 0xec, 0xd4, 0x4a, 0x98, 0xdb, 0xb2,
	0x53, 0x2b, 0x85, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x98, 0xc0, 0x62, 0x10,
	0x8e, 0x15, 0x93, 0x05, 0x63, 0x12, 0x1b, 0xd8, 0xbf, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xbd, 0x2b, 0x09, 0xc4, 0x04, 0x01, 0x00, 0x00,
}
